name: Release

on:
  push:
    branches: 
      - main
      - 'v[0-9]'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:all
      - name: Define Tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi
      - name: Publish Release
        uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish -- --tag ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  